"""
===============================================================================
File Name   : graph_validator.py
Module      : Agent Brain
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Validates the structural integrity of the execution graph generated by the
Graph Builder.

B-5 — DAG Validation

The GraphValidator verifies:

    • node integrity
    • node/task identifier consistency
    • parent references
    • child references
    • parent/child symmetry
    • self-dependencies
    • duplicate dependencies
    • circular dependencies
    • root node availability
    • leaf node availability
    • DAG structural integrity

This module forms the integrity boundary between the Graph Builder and Planner.

Author : Team JARVIS
===============================================================================
"""

from __future__ import annotations
from xml.parsers.expat import errors

from agent_engine.agent_brain.models.execution_graph import ExecutionGraph
from agent_engine.agent_brain.models.graph_validation_result import (
    GraphValidationResult,
)


class GraphValidator:
    """
    Validates the structural integrity of an ExecutionGraph.
    """

    # =========================================================================
    # Public API
    # =========================================================================

    def validate(
        self,
        graph: ExecutionGraph,
    ) -> GraphValidationResult:
        """
        Validate the complete execution graph.

        Returns
        -------
        GraphValidationResult
            Complete structural validation result.
        """

        errors: list[str] = []
        warnings: list[str] = []

        # ---------------------------------------------------------------------
        # Empty graph
        # ---------------------------------------------------------------------

        if graph.node_count == 0:

            warnings.append(
                "Execution graph contains no nodes."
            )

            return GraphValidationResult(
                is_valid=True,
                node_count=0,
                edge_count=0,
                errors=errors,
                warnings=warnings,
                metadata={
                    "validator": "GraphValidator",
                    "status": "empty_graph",
                    "cycle_detected": False,
                    "root_count": 0,
                    "leaf_count": 0,
                },
            )

        # ---------------------------------------------------------------------
        # Node validation
        # ---------------------------------------------------------------------

        self._validate_nodes(
            graph=graph,
            errors=errors,
        )

        # ---------------------------------------------------------------------
        # Dependency validation
        # ---------------------------------------------------------------------

        edge_count = self._validate_dependencies(
            graph=graph,
            errors=errors,
        )

        # ---------------------------------------------------------------------
        # Cycle validation
        # ---------------------------------------------------------------------

        cycle_nodes = self._find_cycle_nodes(graph)

        cycle_detected = bool(cycle_nodes)

        if cycle_detected:

            errors.append(
                "Circular dependency detected in execution graph "
                f"involving task(s): {', '.join(map(str, cycle_nodes))}."
            )
        # ---------------------------------------------------------------------
        # Root / leaf validation
        # ---------------------------------------------------------------------

        calculated_roots = {
            node.node_id
            for node in graph.nodes.values()
            if not node.parents
        }

        calculated_leaves = {
            node.node_id
            for node in graph.nodes.values()
            if not node.children
        }

        if not calculated_roots:

            errors.append(
                "Execution graph contains no root node. "
                "This may indicate a cyclic dependency graph."
            )

        if not calculated_leaves:

            errors.append(
                "Execution graph contains no leaf node. "
                "This may indicate a cyclic dependency graph."
            )

        # ---------------------------------------------------------------------
        # Final validation status
        # ---------------------------------------------------------------------

        is_valid = len(errors) == 0

        return GraphValidationResult(
            is_valid=is_valid,
            node_count=graph.node_count,
            edge_count=edge_count,
            errors=errors,
            warnings=warnings,
            metadata={
                "validator": "GraphValidator",
                "status": (
                    "valid"
                    if is_valid
                    else "invalid"
                ),
                "cycle_detected": cycle_detected,
                "cycle_nodes": cycle_nodes,
                "root_count": len(calculated_roots),
                "leaf_count": len(calculated_leaves),
                "root_nodes": sorted(calculated_roots),
                "leaf_nodes": sorted(calculated_leaves),
            },
        )

    # =========================================================================
    # Node Validation
    # =========================================================================

    def _validate_nodes(
        self,
        graph: ExecutionGraph,
        errors: list[str],
    ) -> None:
        """
        Validate graph node identity and task identity.
        """

        for node_id, node in graph.nodes.items():

            if node.node_id != node_id:

                errors.append(
                    f"Node key {node_id} does not match "
                    f"node_id {node.node_id}."
                )

            if node.task.task_id != node.node_id:

                errors.append(
                    f"Node {node.node_id} task ID "
                    f"{node.task.task_id} does not match node ID."
                )

    # =========================================================================
    # Dependency Validation
    # =========================================================================

    def _validate_dependencies(
        self,
        graph: ExecutionGraph,
        errors: list[str],
    ) -> int:
        """
        Validate parent/child dependency relationships.

        Returns
        -------
        int
            Number of dependency edges discovered.
        """

        edge_count = 0

        for node in graph.nodes.values():

            # -----------------------------------------------------------------
            # Parent references
            # -----------------------------------------------------------------

            for parent_id in node.parents:

                edge_count += 1

                # Self dependency
                if parent_id == node.node_id:

                    errors.append(
                        f"Self-dependency detected: "
                        f"Task {node.node_id} -> "
                        f"Task {node.node_id}."
                    )

                    continue

                parent = graph.get_node(parent_id)

                # Missing parent
                if parent is None:

                    errors.append(
                        f"Task {node.node_id} references "
                        f"missing parent Task {parent_id}."
                    )

                    continue

                # Parent/child asymmetry
                if node.node_id not in parent.children:

                    errors.append(
                        f"Dependency inconsistency: "
                        f"Task {node.node_id} lists Task {parent_id} "
                        f"as parent, but Task {parent_id} does not list "
                        f"Task {node.node_id} as child."
                    )

            # -----------------------------------------------------------------
            # Duplicate parents
            # -----------------------------------------------------------------

            if len(node.parents) != len(set(node.parents)):

                errors.append(
                    f"Task {node.node_id} contains duplicate "
                    f"parent dependencies."
                )

            # -----------------------------------------------------------------
            # Child references
            # -----------------------------------------------------------------

            for child_id in node.children:

                # Self dependency
                if child_id == node.node_id:

                    errors.append(
                        f"Self-dependency detected: "
                        f"Task {node.node_id} -> "
                        f"Task {node.node_id}."
                    )

                    continue

                child = graph.get_node(child_id)

                # Missing child
                if child is None:

                    errors.append(
                        f"Task {node.node_id} references "
                        f"missing child Task {child_id}."
                    )

                    continue

                # Child/parent asymmetry
                if node.node_id not in child.parents:

                    errors.append(
                        f"Dependency inconsistency: "
                        f"Task {node.node_id} lists Task {child_id} "
                        f"as child, but Task {child_id} does not list "
                        f"Task {node.node_id} as parent."
                    )

            # -----------------------------------------------------------------
            # Duplicate children
            # -----------------------------------------------------------------

            if len(node.children) != len(set(node.children)):

                errors.append(
                    f"Task {node.node_id} contains duplicate "
                    f"child dependencies."
                )

        return edge_count

    # =========================================================================
    # Cycle Detection
    # =========================================================================

    # ------------------------------------------------------------------
    # Cycle detection
    # ------------------------------------------------------------------

    def _find_cycle_nodes(
        self,
        graph: ExecutionGraph,
    ) -> list[int]:
        """
        Detect cycle nodes using DFS traversal.

        When a back-edge is found, the complete cycle is extracted from
        the current DFS recursion path.

        Example:

            1 -> 2 -> 3
                ^    |
                |____|

        Returns:

            [1, 2, 3]

        rather than only the nodes directly involved in the detected
        back-edge.
        """

        visited: set[int] = set()
        recursion_stack: set[int] = set()

        # Stores the current DFS path in traversal order.
        path: list[int] = []

        # Stores the nodes belonging to detected cycles.
        cycle_nodes: set[int] = set()

        def dfs(node_id: int) -> bool:
            """
            Perform depth-first traversal and extract complete cycles.
            """

            # --------------------------------------------------------------
            # Back-edge detected
            # --------------------------------------------------------------

            if node_id in recursion_stack:

                # Find where the repeated node appears in the
                # current DFS path.
                try:
                    cycle_start_index = path.index(node_id)
                except ValueError:
                    return True

                # Everything from the repeated node onward belongs
                # to the cycle.
                cycle_nodes.update(
                    path[cycle_start_index:]
                )

                return True

            # --------------------------------------------------------------
            # Already completely processed
            # --------------------------------------------------------------

            if node_id in visited:
                return False

            visited.add(node_id)
            recursion_stack.add(node_id)
            path.append(node_id)

            node = graph.get_node(node_id)

            if node is None:

                recursion_stack.remove(node_id)
                path.pop()

                return False

            # --------------------------------------------------------------
            # Traverse children
            # --------------------------------------------------------------

            for child_id in node.children:

                if child_id in recursion_stack:

                    # A back-edge means a cycle exists.
                    cycle_start_index = path.index(child_id)

                    cycle_nodes.update(
                        path[cycle_start_index:]
                    )

                    continue

                dfs(child_id)

            # --------------------------------------------------------------
            # Backtrack
            # --------------------------------------------------------------

            recursion_stack.remove(node_id)
            path.pop()

            return bool(cycle_nodes)

        # ------------------------------------------------------------------
        # Start DFS from every disconnected component
        # ------------------------------------------------------------------

        for node_id in graph.nodes:

            if node_id not in visited:

                dfs(node_id)

        return sorted(cycle_nodes)