"""
===============================================================================
File Name   : interpreter.py
Module      : Agent Brain
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
The Interpreter converts raw natural language tasks generated by the LLM into
structured InterpretedTask objects.

This module performs only preprocessing and normalization.
No reasoning, intent detection, action resolution, or tool selection is
performed here.

Responsibilities:
    • Read tasks from the ProcessingContext
    • Normalize task descriptions
    • Create InterpretedTask objects
    • Store interpreted tasks back into the ProcessingContext
    • Update processing stage
    • Record processing logs

Author      : Team Agent
===============================================================================
"""

from agent_engine.agent_brain.models.interpreted_task import InterpretedTask
from agent_engine.agent_brain.models.processing_context import ProcessingContext
from agent_engine.contracts.enums import ProcessingStage
from agent_engine.utils.text_normalizer import TextNormalizer


class Interpreter:
    """
    Converts raw LLM task descriptions into structured InterpretedTask objects.
    """

    def __init__(self):
        self._normalizer = TextNormalizer()

    def interpret(self, context: ProcessingContext) -> ProcessingContext:
        """
        Interpret all tasks present in the ProcessingContext.

        Parameters
        ----------
        context : ProcessingContext

        Returns
        -------
        ProcessingContext
        """

        context.current_stage = ProcessingStage.INTERPRETING
        context.log("Task interpretation started.")

        interpreted_tasks = []

        successful_tasks = 0
        failed_tasks = 0

        for task_id, task in enumerate(context.llm_plan.tasks, start=1):

            try:

                normalized_result = self._normalizer.normalize(task)

                interpreted_task = InterpretedTask(
                    task_id=task_id,
                    original_text=task,
                    normalized_text=normalized_result.normalized_text
                )

                interpreted_tasks.append(interpreted_task)

                successful_tasks += 1

                context.log(
                    f"Task {task_id} interpreted successfully."
                )

            except Exception as exception:

                print("=" * 80)
                print(exception)
                print(type(exception))
                print("=" * 80)

                failed_tasks += 1

                context.log(
                    f"Task {task_id} interpretation failed: {exception}"
                )

        context.interpreted_tasks = interpreted_tasks

        context.log(
            f"Interpreter completed. "
            f"Successful: {successful_tasks}, "
            f"Failed: {failed_tasks}"
        )

        return context