"""
===============================================================================
File Name   : validator.py
Module      : Agent Brain
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Performs high-level validation on the LLM execution plan before it enters the
Agent Brain processing pipeline.

The validator assumes that structural validation has already been performed
by the Pydantic LLMPlan model. Therefore, this module focuses only on
business-level validation rules.

Responsibilities:
    • Validate summary quality
    • Validate missing information entries
    • Detect duplicate tasks
    • Check goal-task consistency

Author      : Team Agent
===============================================================================
"""

from collections import Counter

from agent_engine.agent_brain.models.llm_plan import LLMPlan
from agent_engine.agent_brain.models.validation_result import ValidationResult
from agent_engine.contracts.enums import ValidationCode


class BasicValidator:
    """
    Performs business-level validation on an LLM execution plan.
    """

    def validate(self, plan: LLMPlan) -> ValidationResult:
        """
        Validate the execution plan.

        Parameters
        ----------
        plan : LLMPlan
            Raw execution plan generated by the LLM.

        Returns
        -------
        ValidationResult
            Validation status, errors and warnings.
        """

        result = ValidationResult()

        self._validate_summary(plan, result)
        self._validate_missing_information(plan, result)
        self._validate_duplicate_tasks(plan, result)
        self._validate_goal_consistency(plan, result)

        return result

    # ------------------------------------------------------------------
    # Summary Validation
    # ------------------------------------------------------------------

    def _validate_summary(
        self,
        plan: LLMPlan,
        result: ValidationResult
    ) -> None:

        if plan.summary is None:

            result.add_warning(
                ValidationCode.MISSING_SUMMARY,
                "Summary was not provided by the LLM.",
                "summary"
            )
            return

        if len(plan.summary.strip()) < 15:

            result.add_warning(
                ValidationCode.SHORT_SUMMARY,
                "Summary is unusually short.",
                "summary"
            )

    # ------------------------------------------------------------------
    # Missing Information Validation
    # ------------------------------------------------------------------

    def _validate_missing_information(
        self,
        plan: LLMPlan,
        result: ValidationResult
    ) -> None:

        for index, item in enumerate(plan.missing_information):

            if not item.strip():

                result.add_error(
                    ValidationCode.INVALID_MISSING_INFORMATION,
                    "Missing information contains an empty value.",
                    f"missing_information[{index}]"
                )

    # ------------------------------------------------------------------
    # Duplicate Task Detection
    # ------------------------------------------------------------------

    def _validate_duplicate_tasks(
        self,
        plan: LLMPlan,
        result: ValidationResult
    ) -> None:

        normalized_tasks = [
            task.strip().lower()
            for task in plan.tasks
        ]

        duplicates = [
            task
            for task, count in Counter(normalized_tasks).items()
            if count > 1
        ]

        if duplicates:

            result.add_warning(
                ValidationCode.DUPLICATE_TASKS,
                f"Duplicate tasks detected: {', '.join(duplicates)}",
                "tasks"
            )

    # ------------------------------------------------------------------
    # Goal Consistency Validation
    # ------------------------------------------------------------------

    def _validate_goal_consistency(
        self,
        plan: LLMPlan,
        result: ValidationResult
    ) -> None:
        """
        Performs a lightweight consistency check between the goal
        and the generated task list.

        This is intentionally heuristic-based.
        Deep semantic validation belongs to future Agent Brain modules.
        """

        goal = plan.goal.lower()

        task_text = " ".join(plan.tasks).lower()

        keywords = [
            "download",
            "summarize",
            "search",
            "open",
            "rename",
            "delete",
            "move",
            "copy"
        ]

        missing_keywords = []

        for keyword in keywords:

            if keyword in goal and keyword not in task_text:

                missing_keywords.append(keyword)

        if missing_keywords:

            result.add_warning(
                ValidationCode.GOAL_TASK_MISMATCH,
                (
                    "Some goal keywords were not found in the generated "
                    f"tasks: {', '.join(missing_keywords)}"
                ),
                "goal"
            )