"""
===============================================================================
File Name   : execution_graph.py
Module      : Agent Brain Models
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Represents the complete execution graph generated by the Graph Builder.

The ExecutionGraph stores all execution nodes and their dependency
relationships. It serves as the central planning structure used by the
Planner, Dispatcher, Scheduler, and Monitoring modules.

The graph follows a Directed Acyclic Graph (DAG) architecture where each
ExecutionNode represents an executable task and edges represent execution
dependencies.

Author      : Team JARVIS
===============================================================================
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from agent_engine.agent_brain.models.execution_node import ExecutionNode


class ExecutionGraph(BaseModel):
    """
    Represents the complete execution dependency graph.
    """

    # ------------------------------------------------------------------
    # Graph Nodes
    # ------------------------------------------------------------------

    nodes: dict[int, ExecutionNode] = Field(
        default_factory=dict
    )

    # ------------------------------------------------------------------
    # Graph Metadata
    # ------------------------------------------------------------------

    graph_metadata: dict[str, str] = Field(
        default_factory=dict
    )
    dependency_metadata: dict[str, dict[str, str]] = Field(
        default_factory=dict
    )

    # ------------------------------------------------------------------
    # Configuration
    # ------------------------------------------------------------------

    model_config = {
        "validate_assignment": True,
        "extra": "forbid"
    }

    # ------------------------------------------------------------------
    # Node Management
    # ------------------------------------------------------------------

    def add_node(self, node: ExecutionNode) -> None:
        """
        Adds a node to the execution graph.
        """

        self.nodes[node.node_id] = node

    def get_node(self, node_id: int) -> ExecutionNode | None:
        """
        Returns a node by its identifier.
        """

        return self.nodes.get(node_id)

    def has_node(self, node_id: int) -> bool:
        """
        Checks whether the graph contains the node.
        """

        return node_id in self.nodes

    # ------------------------------------------------------------------
    # Edge Management
    # ------------------------------------------------------------------

    def add_dependency(
        self,
        parent_id: int,
        child_id: int,
        dependency_type: str | None = None,
        confidence: float | None = None,
        reason: str | None = None,
        metadata: dict[str, str] | None = None,
    ) -> None:
        """
        Creates a dependency between two nodes and stores
        dependency detection metadata.
        """
        if parent_id == child_id:
            raise ValueError(
                f"Self-dependency is not allowed: "
                f"Task {parent_id} -> Task {child_id}."
            )

        parent = self.get_node(parent_id)
        child = self.get_node(child_id)

        if parent is None:
            raise ValueError(
                f"Parent node {parent_id} does not exist."
            )

        if child is None:
            raise ValueError(
                f"Child node {child_id} does not exist."
            )

        parent.add_child(child_id)
        child.add_parent(parent_id)

        dependency_key = f"{parent_id}->{child_id}"

        self.dependency_metadata[dependency_key] = {
            "dependency_type": (
                dependency_type.value
                if hasattr(dependency_type, "value")
                else str(dependency_type)
            ),
            "confidence": str(confidence),
            "reason": reason or "",
            **(metadata or {}),
        }

    def get_dependency_metadata(
        self,
        parent_id: int,
        child_id: int,
    ) -> dict[str, str] | None:
        """
        Returns metadata associated with a dependency edge.
        """

        dependency_key = f"{parent_id}->{child_id}"

        return self.dependency_metadata.get(
            dependency_key
        )
    # ------------------------------------------------------------------
    # Graph Information
    # ------------------------------------------------------------------

    @property
    def node_count(self) -> int:
        """
        Returns the total number of nodes.
        """

        return len(self.nodes)

    @property
    def root_nodes(self) -> list[ExecutionNode]:
        """
        Returns nodes with no parent dependencies.
        """

        return [
            node
            for node in self.nodes.values()
            if not node.parents
        ]

    @property
    def leaf_nodes(self) -> list[ExecutionNode]:
        """
        Returns nodes that have no children.
        """

        return [
            node
            for node in self.nodes.values()
            if not node.children
        ]

    # ------------------------------------------------------------------
    # Root / Leaf Recalculation
    # ------------------------------------------------------------------

    def recalculate_roots_and_leaves(self) -> tuple[list[int], list[int]]:
        """
        Recalculate root and leaf node identifiers from the current
        dependency relationships.

        A root node has no parents.

        A leaf node has no children.

        Returns:
            tuple[list[int], list[int]]:
                (root_node_ids, leaf_node_ids)
        """

        root_ids = [
            node.node_id
            for node in self.nodes.values()
            if not node.parents
        ]

        leaf_ids = [
            node.node_id
            for node in self.nodes.values()
            if not node.children
        ]

        return root_ids, leaf_ids

    # ------------------------------------------------------------------
    # Execution Readiness
    # ------------------------------------------------------------------

    def is_execution_ready(self) -> bool:
        """
        Determines whether the execution graph is ready to be consumed
        by the Planner.

        The graph is execution-ready when:

            • at least one node exists
            • every node has a valid task
            • task IDs match node IDs
            • parent references point to existing nodes
            • child references point to existing nodes
            • parent/child relationships are synchronized
            • no self-dependencies exist
            • no duplicate dependencies exist
            • the graph contains at least one root
            • the graph contains at least one leaf

        Cycle detection remains the responsibility of GraphValidator.
        """

        if self.node_count == 0:
            return False

        for node_id, node in self.nodes.items():

            # ----------------------------------------------------------
            # Node identity
            # ----------------------------------------------------------

            if node.node_id != node_id:
                return False

            if node.task.task_id != node_id:
                return False

            # ----------------------------------------------------------
            # Parent integrity
            # ----------------------------------------------------------

            if len(node.parents) != len(set(node.parents)):
                return False

            for parent_id in node.parents:

                if parent_id == node_id:
                    return False

                parent = self.get_node(parent_id)

                if parent is None:
                    return False

                if node_id not in parent.children:
                    return False

            # ----------------------------------------------------------
            # Child integrity
            # ----------------------------------------------------------

            if len(node.children) != len(set(node.children)):
                return False

            for child_id in node.children:

                if child_id == node_id:
                    return False

                child = self.get_node(child_id)

                if child is None:
                    return False

                if node_id not in child.parents:
                    return False

        # --------------------------------------------------------------
        # Root / leaf availability
        # --------------------------------------------------------------

        if not self.root_nodes:
            return False

        if not self.leaf_nodes:
            return False

        return True

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """
        Removes every node from the graph.
        """

        self.nodes.clear()
        self.graph_metadata.clear()
        self.dependency_metadata.clear()