"""
===============================================================================
File Name   : llm_plan.py
Module      : Agent Brain Models
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Defines the raw execution plan received from the LLM.

This model represents the high-level intent generated by the LLM before any
processing, enrichment, or execution planning is performed.

The Agent Brain uses this object as the input for validation and task
interpretation.

Author      : Team Agent
===============================================================================
"""

from typing import List

from pydantic import BaseModel, Field, field_validator


class LLMPlan(BaseModel):
    """
    Raw execution plan generated by the LLM.

    This model intentionally remains lightweight.
    The Agent Brain is responsible for converting this into an executable
    execution plan.
    """

    goal: str = Field(
        ...,
        description="Primary objective of the user's request."
    )

    summary: str | None = Field(
        default=None,
        description="Optional summary generated by the LLM."
    )

    missing_information: List[str] = Field(
        default_factory=list,
        description="Information that may require user clarification."
    )

    tasks: List[str] = Field(
        ...,
        description="High-level tasks generated by the LLM."
    )

    @field_validator("goal")
    @classmethod
    def validate_goal(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("Goal cannot be empty.")

        return value

    @field_validator("tasks")
    @classmethod
    def validate_tasks(cls, value: List[str]) -> List[str]:

        if len(value) == 0:
            raise ValueError("At least one task must be present.")

        cleaned_tasks = []

        for task in value:

            task = task.strip()

            if not task:
                raise ValueError("Task description cannot be empty.")

            cleaned_tasks.append(task)

        return cleaned_tasks

    model_config = {
        "extra": "forbid",
        "validate_assignment": True
    }