"""
===============================================================================
File Name   : request_metadata.py
Module      : Agent Brain Models
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Represents runtime metadata associated with an Agent request.

This metadata is generated by the Agent Brain and is independent of the
LLM output. It is used for tracking, monitoring, debugging, and future
execution management.

Author      : Team Agent
===============================================================================
"""

from datetime import datetime

from pydantic import BaseModel, Field


class RequestMetadata(BaseModel):
    """
    Runtime metadata associated with a processing request.
    """

    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the request entered the Agent Brain."
    )

    agent_version: str = Field(
        default="1.0.0",
        description="Current version of the Agent Brain."
    )

    pipeline: str = Field(
        default="Agent Brain",
        description="Processing pipeline responsible for the request."
    )

    status: str = Field(
        default="READY",
        description="Current lifecycle status of the request."
    )

    source: str = Field(
        default="LLM",
        description="Origin of the request."
    )

    retry_count: int = Field(
        default=0,
        ge=0,
        description="Number of retries attempted for this request."
    )

    model_config = {
        "validate_assignment": True,
        "extra": "forbid"
    }