"""
===============================================================================
File Name   : run_module4_demo.py
Module      : Demonstrations
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Final live demonstration runner for Module 4.

This demonstration uses the actual LLM-team output defined in
sample_llm_outputs.py and passes it through the real Agent Brain and
Agent Orchestrator pipeline.

Pipeline:

Actual LLM Team Output
        ↓
LLMPlan
        ↓
Validation
        ↓
Interpretation
        ↓
Graph Builder
        ↓
Graph Validation
        ↓
Planner
        ↓
Agent Orchestrator
        ↓
Decision Manager
        ↓
State Manager
        ↓
Action Dispatcher
        ↓
Module 5 Automation Boundary

IMPORTANT:
----------
Module 5 automation is intentionally NOT executed.

The Action Dispatcher used here is a demonstration implementation of the
existing Module 4 execution boundary. It reports that an action reached the
dispatcher interface and returns a successful ExecutionOutcome.

No browser, desktop, file-system, or external automation is performed.

Author : Team JARVIS
===============================================================================
"""

from __future__ import annotations

from agent_engine.agent_brain.models.llm_plan import LLMPlan
from agent_engine.contracts.enums import ExecutionStatus, ResultStatus
from agent_engine.decision_manager.models.execution_outcome import ExecutionOutcome
from agent_engine.dispatcher.action_dispatcher import ActionDispatcher
from agent_engine.events.event_bus import AgentEvent, EventBus
from agent_engine.orchestration.agent_orchestrator import AgentOrchestrator

from agent_engine.tests.integration.sample_llm_outputs import (
    SPRING_AI_CASE,
)


# =============================================================================
# Formatting
# =============================================================================

LINE = "═" * 90
SUB_LINE = "-" * 90


def print_banner(title: str) -> None:
    print("\n")
    print(LINE)
    print(title.center(90))
    print(LINE)


def print_subtitle(title: str) -> None:
    print(f"\n{title}")
    print(SUB_LINE)


# =============================================================================
# Demo Dispatcher
# =============================================================================


class Module4DemoDispatcher:
    """
    Demonstration implementation of the Module 4 ActionDispatcher contract.

    This dispatcher does NOT execute real automation.

    It only proves that the fully planned task reaches the execution
    boundary and that a normalized ExecutionOutcome is returned to the
    Agent Orchestrator.
    """

    def __init__(self) -> None:
        self.calls: list[tuple[int, int, str]] = []

    def dispatch(
        self,
        task,
        *,
        attempt: int,
        timeout_seconds: float | None = None,
    ) -> ExecutionOutcome:

        task_id = task.task_id
        action_text = task.original_text

        self.calls.append(
            (
                task_id,
                attempt,
                action_text,
            )
        )

        print(
            f"[DISPATCHER] Task {task_id} → execution interface reached"
        )

        print(
            f"             Action : {action_text}"
        )

        print(
            f"             Attempt: {attempt}"
        )

        return ExecutionOutcome(
            task_id=task_id,
            status=ExecutionStatus.COMPLETED,
            success=True,
            attempt=attempt,
            retry_count=max(attempt - 1, 0),
            max_retries=0,
        )


# =============================================================================
# Event Listener
# =============================================================================


def event_listener(event: AgentEvent) -> None:
    """
    Displays orchestration events generated by the real EventBus.
    """

    if event.name == "request.started":

        print("[EVENT] request.started")
        print(
            f"        goal: {event.payload.get('goal')}"
        )

    elif event.name == "request.completed":

        print("[EVENT] request.completed")
        print(
            f"        task_count: "
            f"{event.payload.get('task_count')}"
        )

    elif event.name == "request.failed":

        print("[EVENT] request.failed")
        print(
            f"        error: "
            f"{event.payload.get('error')}"
        )

    elif event.name == "task.ready":

        print(
            f"[EVENT] task.ready | Task {event.task_id}"
        )

    elif event.name == "task.started":

        print(
            f"[EVENT] task.started | Task {event.task_id}"
        )

        print(
            f"        attempt: "
            f"{event.payload.get('attempt')}"
        )

    elif event.name == "task.decision":

        print(
            f"[EVENT] task.decision | Task {event.task_id}"
        )

        print(
            f"        action: "
            f"{event.payload.get('action')}"
        )

        print(
            f"        attempt: "
            f"{event.payload.get('attempt')}"
        )

        print(
            f"        reason: "
            f"{event.payload.get('reason')}"
        )

    elif event.name == "task.completed":

        print(
            f"[EVENT] task.completed | Task {event.task_id}"
        )

    elif event.name == "task.failed":

        print(
            f"[EVENT] task.failed | Task {event.task_id}"
        )

        print(
            f"        action: "
            f"{event.payload.get('action')}"
        )

        print(
            f"        reason: "
            f"{event.payload.get('reason')}"
        )


# =============================================================================
# LLM Input Display
# =============================================================================


def print_actual_llm_input(llm_output: dict) -> None:
    """
    Displays the actual LLM-team output before it enters Module 4.

    No transformation is performed here.
    """

    print_banner("ACTUAL LLM TEAM OUTPUT")

    print_subtitle("Source")

    print(
        "sample_llm_outputs.py → SPRING_AI_CASE"
    )

    print_subtitle("Goal")

    print(llm_output["goal"])

    print_subtitle("Summary")

    print(llm_output["summary"])

    print_subtitle("Missing Information")

    if llm_output.get("missing_information"):

        for item in llm_output["missing_information"]:
            print(f"• {item}")

    else:

        print("None")

    print_subtitle("Tasks")

    for index, task in enumerate(
        llm_output["tasks"],
        start=1,
    ):
        print(
            f"{index}. {task}"
        )


# =============================================================================
# Module 4 Result
# =============================================================================


def print_module4_result(
    result,
    dispatcher: Module4DemoDispatcher,
) -> None:

    print_banner(
        "MODULE 4 : AGENT BRAIN EXECUTION RESULT"
    )

    print_subtitle("Request ID")

    print(result.request_id)

    print_subtitle("Overall Result")

    print(result.status)

    print_subtitle("Planning")

    if result.planning_result is not None:

        print(
            f"Total Steps : "
            f"{result.planning_result.total_steps}"
        )

        print(
            f"Plan Valid  : "
            f"{result.planning_result.is_valid}"
        )

    else:

        print("Planning Result : NOT AVAILABLE")

    print_subtitle("Execution Outcomes")

    if result.outcomes:

        for outcome in result.outcomes:

            print(
                f"Task {outcome.task_id} | "
                f"Attempt {outcome.attempt} | "
                f"Success {outcome.success} | "
                f"Status {outcome.status}"
            )

    else:

        print("None")

    print_subtitle("Decision Results")

    if result.decisions:

        for decision in result.decisions:

            print(
                f"Task {decision.task_id} | "
                f"Decision {decision.action.value} | "
                f"Reason: {decision.reason}"
            )

    else:

        print("None")

    print_subtitle("Runtime States")

    if result.planning_result is not None:

        for task_id in result.planning_result.execution_order:

            status = (
                result.context
                and result.context.execution_graph
            )

            runtime_status = (
                orchestrator.state_manager.get_status(task_id)
            )

            print(
                f"Task {task_id} | "
                f"{runtime_status}"
            )

    else:

        print("None")

    print_subtitle("Dispatcher Calls")

    if dispatcher.calls:

        for task_id, attempt, task_text in dispatcher.calls:

            print(
                f"Task {task_id} → Attempt {attempt}"
            )

            print(
                f"  Task: {task_text}"
            )

    else:

        print("None")

    print_subtitle("Execution Boundary")

    print(
        "Agent Brain        : COMPLETE"
    )

    print(
        "Decision Manager   : COMPLETED"
    )

    print(
        "State Manager      : COMPLETED"
    )

    print(
        "Action Dispatcher  : INTERFACE EXECUTED"
    )

    print(
        "Automation Engine  : NOT IMPLEMENTED"
    )

    print(
        "Module 5           : NEXT DEVELOPMENT MODULE"
    )


# =============================================================================
# Main Demonstration
# =============================================================================


def main() -> None:

    # -------------------------------------------------------------------------
    # Actual LLM-Team Output
    # -------------------------------------------------------------------------

    llm_output = SPRING_AI_CASE

    print_banner(
        "JARVIS MODULE 4 — FINAL LIVE DEMONSTRATION"
    )

    print(
        "This demonstration uses the actual LLM-team output."
    )

    print(
        "The output is passed unchanged into the real Module 4 Agent Brain."
    )

    print(
        "Module 5 automation is intentionally NOT executed."
    )

    print(
        "The Action Dispatcher shown here represents the existing "
        "Module 4 execution boundary."
    )

    # -------------------------------------------------------------------------
    # Display actual input
    # -------------------------------------------------------------------------

    print_actual_llm_input(llm_output)

    # -------------------------------------------------------------------------
    # Build real Module 4 components
    # -------------------------------------------------------------------------

    dispatcher = Module4DemoDispatcher()

    event_bus = EventBus()

    event_bus.subscribe(
        "*",
        event_listener,
    )

    orchestrator_instance = AgentOrchestrator(
        dispatcher,
        event_bus=event_bus,
    )

    # Make the result printer able to inspect the actual StateManager.
    global orchestrator
    orchestrator = orchestrator_instance

    # -------------------------------------------------------------------------
    # Convert actual LLM output into the canonical LLMPlan
    # -------------------------------------------------------------------------

    print_banner(
        "MODULE 4 : AGENT BRAIN PROCESSING"
    )

    print(
        "Passing actual LLM-team output to AgentOrchestrator..."
    )

    print(
        "The real Module 4 pipeline will now execute:"
    )

    print(
        "LLMPlan → Validation → Interpretation → "
        "Graph → Planning → Orchestration"
    )

    print()

    plan = LLMPlan(
        **llm_output
    )

    # -------------------------------------------------------------------------
    # Execute the REAL Agent Orchestrator
    # -------------------------------------------------------------------------

    result = orchestrator_instance.run(plan)

    # -------------------------------------------------------------------------
    # Display result
    # -------------------------------------------------------------------------

    print_module4_result(
        result,
        dispatcher,
    )

    # -------------------------------------------------------------------------
    # Final status
    # -------------------------------------------------------------------------

    print("\n" + LINE)

    if result.status == ResultStatus.SUCCESS:

        print(
            "MODULE 4 AGENT BRAIN LIVE DEMONSTRATION "
            "COMPLETED SUCCESSFULLY"
        )

    else:

        print(
            "MODULE 4 AGENT BRAIN LIVE DEMONSTRATION "
            "COMPLETED WITH FAILURE"
        )

    print(LINE)


# =============================================================================
# Entry Point
# =============================================================================


if __name__ == "__main__":
    main()