"""
===============================================================================
File Name   : pipeline_printer.py
Module      : Integration Tests
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Provides formatted console output for the complete Agent Brain pipeline.

This module contains only printing utilities. It does not execute any business
logic.

Author : Team JARVIS
===============================================================================
"""

from __future__ import annotations

from agent_engine.agent_brain.models.processing_context import ProcessingContext
from agent_engine.agent_brain.models.execution_graph import ExecutionGraph
from agent_engine.agent_brain.models.planning_result import PlanningResult


# =============================================================================
# Formatting
# =============================================================================

LINE = "═" * 90
SUB_LINE = "-" * 90


# =============================================================================
# Common Helpers
# =============================================================================

def print_banner(title: str) -> None:
    """
    Prints a section banner.
    """

    print("\n")
    print(LINE)
    print(title.center(90))
    print(LINE)


def print_subtitle(title: str) -> None:
    """
    Prints a subsection title.
    """

    print(f"\n{title}")
    print(SUB_LINE)


# =============================================================================
# LLM OUTPUT
# =============================================================================

def print_llm_output(context: ProcessingContext) -> None:
    """
    Prints the actual LLM-generated plan received by the Agent Brain.
    """

    print_banner("STAGE 0 : LLM PLAN")

    plan = context.llm_plan

    print_subtitle("Goal")
    print(plan.goal)

    print_subtitle("Summary")
    print(plan.summary)

    print_subtitle("Missing Information")

    if plan.missing_information:

        for item in plan.missing_information:
            print(f"• {item}")

    else:
        print("None")

    print_subtitle("Tasks")

    for index, task in enumerate(plan.tasks, start=1):
        print(f"{index}. {task}")


# =============================================================================
# VALIDATOR
# =============================================================================

def print_validator(
    context: ProcessingContext,
    validation=None,
) -> None:
    """
    Prints the actual validator result.

    The validation object is passed from the pipeline runner. This function
    only displays the result and does not perform validation itself.
    """

    print_banner("STAGE 1 : VALIDATION")

    print(f"Current Stage : {context.current_stage}")

    if validation is None:
        print("\nValidation Result : NOT AVAILABLE")
        return

    print(f"Valid         : {validation.is_valid}")

    errors = getattr(validation, "errors", [])

    print(f"Error Count   : {len(errors)}")

    if errors:

        print("\nValidation Errors")

        for error in errors:
            print(f"  - {error}")

    else:

        print("\nValidation Status : PASSED")


# =============================================================================
# INTERPRETER
# =============================================================================

def print_interpreter(context: ProcessingContext) -> None:
    """
    Prints the actual interpreted tasks produced by the Interpreter.
    """

    print_banner("STAGE 2 : INTERPRETATION")

    print(f"Tasks Interpreted : {len(context.interpreted_tasks)}")

    if not context.interpreted_tasks:

        print("\nNo tasks were interpreted.")
        return

    for task in context.interpreted_tasks:

        print(f"\nTask {task.task_id}")

        print(SUB_LINE)

        print(f"Original Text   : {task.original_text}")
        print(f"Normalized Text : {task.normalized_text}")
        print(f"Action          : {task.action}")
        print(f"Tool            : {task.tool}")


# =============================================================================
# GRAPH BUILDER
# =============================================================================

def print_graph(graph: ExecutionGraph) -> None:
    """
    Prints the actual execution graph generated by the Graph Builder.
    """

    print_banner("STAGE 3 : GRAPH BUILDER")

    print(f"Node Count : {graph.node_count}")

    print("\nRoot Nodes")

    if graph.root_nodes:

        for node in graph.root_nodes:
            print(f"• Node {node.node_id}")

    else:

        print("None")

    print("\nLeaf Nodes")

    if graph.leaf_nodes:

        for node in graph.leaf_nodes:
            print(f"• Node {node.node_id}")

    else:

        print("None")

    print("\nExecution Graph")

    print(SUB_LINE)

    for node in graph.nodes.values():

        print(f"\nNode {node.node_id}")

        print(f"Task     : {node.task.original_text}")
        print(f"Parents  : {node.parents}")
        print(f"Children : {node.children}")


# =============================================================================
# GRAPH VALIDATION
# =============================================================================

def print_graph_validation(context: ProcessingContext) -> None:
    """
    Prints the actual graph validation result produced by the Agent Brain.
    """

    print_banner("STAGE 3A : GRAPH VALIDATION")

    result = getattr(
        context,
        "graph_validation_result",
        None,
    )

    if result is None:

        print("Graph Validation Result : NOT AVAILABLE")
        return

    print(f"Graph Valid : {result.is_valid}")

    if hasattr(result, "node_count"):
        print(f"Node Count  : {result.node_count}")

    errors = getattr(result, "errors", [])

    print(f"Error Count : {len(errors)}")

    if errors:

        print("\nGraph Validation Errors")

        for error in errors:
            print(f"  - {error}")

    else:

        print("\nGraph Validation Status : PASSED")


# =============================================================================
# PLANNER
# =============================================================================

def print_planner(
    plan: PlanningResult,
    graph: ExecutionGraph | None = None,
) -> None:
    """
    Prints the actual planning result.

    Important:
    -----------
    PlanningResult.execution_order currently contains node IDs rather than
    ExecutionNode objects. The graph is therefore used to resolve each ID
    back to its corresponding task for readable terminal output.
    """

    print_banner("STAGE 4 : PLANNER")

    print(f"Plan Valid       : {plan.is_valid}")
    print(f"Total Steps      : {plan.total_steps}")
    print(f"Estimated Time   : {plan.estimated_time}")

    print("\nExecution Order")

    print(SUB_LINE)

    if not plan.execution_order:

        print("None")

    else:

        for position, node_id in enumerate(
            plan.execution_order,
            start=1,
        ):

            if graph is not None:

                node = graph.get_node(node_id)

            else:

                node = None

            if node is not None:

                print(
                    f"{position}. "
                    f"Node {node_id} → "
                    f"{node.task.original_text}"
                )

            else:

                print(
                    f"{position}. "
                    f"Node {node_id}"
                )

    print("\nParallel Groups")

    print(SUB_LINE)

    if plan.parallel_groups:

        for level, group in enumerate(
            plan.parallel_groups,
            start=1,
        ):

            print(f"Level {level} : {group}")

    else:

        print("None")

    print("\nPlanning Notes")

    if plan.planning_notes:

        for note in plan.planning_notes:
            print(f"• {note}")

    else:

        print("None")


# =============================================================================
# PROCESSING LOGS
# =============================================================================

def print_logs(context: ProcessingContext) -> None:
    """
    Prints the actual processing logs generated by the Agent Brain.
    """

    print_banner("PROCESSING LOGS")

    if not context.processing_logs:

        print("No processing logs available.")
        return

    for log in context.processing_logs:
        print(log)


# =============================================================================
# FINAL AGENT BRAIN SUMMARY
# =============================================================================

def print_pipeline_summary(context: ProcessingContext) -> None:
    """
    Prints the final Agent Brain processing summary.

    This summary represents the actual completed Agent Brain pipeline.
    It does not claim that Module 5 automation has executed.
    """

    print_banner("AGENT BRAIN SUMMARY")

    print("Pipeline Components")
    print(SUB_LINE)

    print("  LLM Plan           : RECEIVED")
    print("  Validation         : COMPLETED")
    print("  Interpretation     : COMPLETED")
    print("  Graph Construction : COMPLETED")
    print("  Graph Validation   : COMPLETED")
    print("  Planning           : COMPLETED")

    print("\nAgent Brain State")
    print(SUB_LINE)

    if context.execution_graph:

        print(
            f"  Execution Graph    : READY "
            f"({context.execution_graph.node_count} nodes)"
        )

    else:

        print("  Execution Graph    : NOT AVAILABLE")

    if context.execution_plan:

        print(
            f"  Execution Plan     : READY "
            f"({context.execution_plan.total_steps} steps)"
        )

    else:

        print("  Execution Plan     : NOT AVAILABLE")

    print("\nExecution Boundary")
    print(SUB_LINE)

    print("  Agent Brain        : COMPLETE")
    print("          ↓")
    print("  Action Dispatcher  : EXECUTION INTERFACE")
    print("          ↓")
    print("  Module 5           : AUTOMATION / IN PROGRESS")

    print("\n" + LINE)

    print(
        "AGENT BRAIN SUCCESSFULLY PROCESSED "
        "THE LLM-GENERATED PLAN"
    )

    print(LINE)