"""
===============================================================================
File Name   : execution_plan.py
Module      : Contracts
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Defines the ExecutionPlan model received from the LLM.

The ExecutionPlan represents one complete execution request. It contains
request metadata, execution configuration, and a list of executable tasks.

Every request entering the Agent Engine is first converted into an
ExecutionPlan object before validation and execution.

Author      : Team Agent
===============================================================================
"""

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field

from agent_engine.contracts.enums import ExecutionMode
from agent_engine.contracts.task import Task


class ExecutionPlan(BaseModel):
    """
    Represents a complete execution plan generated by the LLM.

    An ExecutionPlan consists of:
        • Request metadata
        • Execution configuration
        • List of executable tasks
    """

    # -------------------------------------------------------------------------
    # Request Information
    # -------------------------------------------------------------------------

    request_id: str = Field(
        ...,
        description="Unique identifier for this execution request."
    )

    goal: str = Field(
        ...,
        description="Primary objective of the request."
    )

    summary: str = Field(
        ...,
        description="Brief summary of the execution plan."
    )

    # -------------------------------------------------------------------------
    # Execution Configuration
    # -------------------------------------------------------------------------

    execution_mode: ExecutionMode = Field(
        default=ExecutionMode.SEQUENTIAL,
        description="Determines how tasks should be executed."
    )

    requires_confirmation: bool = Field(
        default=False,
        description="Whether user confirmation is required before execution."
    )

    missing_information: List[str] = Field(
        default_factory=list,
        description="Missing information required before execution."
    )

    # -------------------------------------------------------------------------
    # Execution Tasks
    # -------------------------------------------------------------------------

    steps: List[Task] = Field(
        ...,
        description="List of executable tasks."
    )

    # -------------------------------------------------------------------------
    # Runtime Metadata
    # -------------------------------------------------------------------------

    received_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the Agent Engine received the request."
    )

    schema_version: str = Field(
        default="1.0",
        description="Execution Plan schema version."
    )

    class Config:
        """
        Pydantic configuration.
        """

        validate_assignment = True
        extra = "forbid"