"""
===============================================================================
File Name   : task.py
Module      : Contracts
Project     : JARVIS - Agent Decision Engine & Automation Engine

Description:
-------------
Defines the internal Task model used by the Agent Engine.

Every step received from the LLM Execution Plan is converted into a Task
object before entering the execution pipeline.

The Task model acts as the central data structure passed through the
Validator, Scheduler, Dispatcher, Controllers, Monitoring, and Result
Generation modules.

Author      : Team Agent
===============================================================================
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from agent_engine.contracts.enums import (
    ExecutionStatus,
    Priority,
    ToolType,
)


class Task(BaseModel):
    """
    Represents one executable task within an execution plan.

    A Task is created from one step of the Execution Plan JSON
    generated by the LLM.
    """

    # -------------------------------------------------------------------------
    # Fields received from LLM
    # -------------------------------------------------------------------------

    id: int = Field(..., description="Unique task identifier")

    description: str = Field(
        ...,
        description="Human-readable description of the task"
    )

    action: str = Field(
        ...,
        description="Action to be executed"
    )

    tool: ToolType = Field(
        ...,
        description="Target automation controller"
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Action parameters"
    )

    depends_on: list[int] = Field(
        default_factory=list,
        description="Task dependencies"
    )

    priority: Priority = Field(
        default=Priority.MEDIUM,
        description="Task priority"
    )

    confirmation_required: bool = Field(
        default=False,
        description="Whether user confirmation is required"
    )

    timeout: int = Field(
        default=60,
        ge=1,
        description="Execution timeout in seconds"
    )

    retry: int = Field(
        default=0,
        ge=0,
        description="Maximum retry attempts"
    )

    # -------------------------------------------------------------------------
    # Runtime Fields (Managed by Agent Engine)
    # -------------------------------------------------------------------------

    status: ExecutionStatus = Field(
        default=ExecutionStatus.PENDING,
        description="Current execution status"
    )

    retry_count: int = Field(
        default=0,
        description="Current retry attempt"
    )

    start_time: datetime | None = None

    end_time: datetime | None = None

    execution_time: float | None = None

    error_message: str | None = None

    # -------------------------------------------------------------------------
    # Future Scalability
    # -------------------------------------------------------------------------

    parent_tasks: list[int] = Field(default_factory=list)

    child_tasks: list[int] = Field(default_factory=list)

    metadata: dict[str, Any] = Field(default_factory=dict)

    class Config:
        """
        Pydantic configuration.
        """

        validate_assignment = True
        extra = "forbid"